<a href="https://colab.research.google.com/github/lunayee/distance/blob/main/%E6%9C%80%E7%9F%AD%E8%B7%AF%E5%BE%91.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Floyd-Warshall 最短路徑

In [1]:
import numpy as np
import pandas as pd

inf = 99999999
e = np.zeros((10,10), dtype = np.int)

n, m = map(int, input().split(' '))

#initialize
for i in range(1, n+1):
	for j in range(1, n+1):
		if i==j:
			e[i][j]=0
		else:
			e[i][j]=inf

#read line
for i in range(1, m+1):
	t1, t2, t3 = map(int, input().split(' '))
	e[t1][t2]=t3

#Floyd-Warshall algorithm
for k in range(1, n+1):
	for i in range(1, n+1):
		for j in range(1, n+1):
			if e[i][j] > e[i][k]+e[k][j]:
				e[i][j] = e[i][k]+e[k][j]

# test data:
# 4 8
# 1 2 2
# 1 3 6
# 1 4 4
# 2 3 3
# 3 1 7
# 3 4 1
# 4 1 5
# 4 3 12

#output final consequences
for i in range(1, n+1):
    print(e[i][1:n+1])

# ---------------------
# [0 2 5 4]
# [9 0 3 4]
# [6 8 0 1]
# [ 5  7 10  0]


4 8
1 2 2
1 3 6
1 4 4
2 3 3
3 1 7
3 4 1
4 1 5
4 3 12
[0 2 5 4]
[9 0 3 4]
[6 8 0 1]
[ 5  7 10  0]


# Dijkstra 最短路徑

In [ ]:
import numpy as np

e = np.zeros((11, 11), dtype=int)
inf = 99999999
key_point = 1

# 讀入頂點個數，邊個數
n, m = map(int, input().split(' '))
# 初始化
for i in range(1, n+1):
    for j in range(1, n+1):
        if i == j : 
            e[i][j] = 0
        else:
            e[i][j] = inf

# 讀入邊
for i in range(1, m+1):
    t1, t2, t3 = map(int, input().split(' '))
    e[t1][t2] = t3

# 初始 dis 陣列，從 key_point 到其餘各點的初始路程
dis = np.zeros(11, dtype=int)
for i in range(1, n+1):
    dis[i] = e[key_point][i]

# 初始 book 陣列
book = np.zeros(11, dtype=int)
book[key_point] = 1

# Dijkstra Algorithm
for i in range(1, n):
    # 找到離 key_point 點最近的頂點
    min = inf
    for j in range(1, n+1):
        if book[j] == 0 and dis[j] < min :
            min = dis[j]
            u = j
    book[u] = 1
    for v in range(1, n+1):
        if e[u][v] < inf:
            if dis[v] > dis[u] + e[u][v]:
                dis[v] = dis[u] + e[u][v]

# 輸出 原點到所有頂點的最短距離
for i in range(1, n+1):
    print(dis[i])


'''
驗證資料:
6 9
1 2 1
1 3 12
2 3 9
2 4 3
3 5 5
4 3 4
4 5 13
4 6 15
5 6 4
'''


# Bellman-Ford 最短路徑

In [ ]:
import numpy as np

n, m = map(int, input().split(' '))

dis = np.zeros(10, dtype=np.int)
bak = np.zeros(10, dtype=np.int)

u = np.zeros(10, dtype=np.int)
v = np.zeros(10, dtype=np.int)
w = np.zeros(10, dtype=np.int)
inf = 99999999

# 讀入邊
for i in range(1, m+1):
    u[i], v[i], w[i] = map(int, input().split(' '))

# 初始化 dis 陣列，此處用 1 號頂點到其餘各點的初始路程
for i in range(1, n+1):
    dis[i] = inf
dis[1] = 0

# Bellman-Ford Algorithm
for k in range(1, n):
    # 將 dis 陣列備份到 bak 陣列中
    for i in range(1, n+1):
        bak[i] = dis[i]
    # 進行一輪鬆弛
    for i in range(1, m+1):
        if dis[v[i]] > dis[u[i]] + w[i] :
            dis[v[i]] = dis[u[i]] + w[i]
    # 鬆弛完畢檢測 dis 陣列有無更新
    check = 0
    for i in range(1, n+1):
        if bak[i] != dis[i]:
            check = 1
            break
    # 如果 dis 陣列沒有更新，提前退出演算法迴圈
    if check == 0:
        break

# 檢測負權迴路
flag = 0
for i in range(1, m+1):
    if dis[v[i]] > dis[u[i]] + w[i]:
        flag = 1
if flag == 1 :
    print("此圖含有負權迴路")
else:
    # 輸出最終結果
    for i in range(1, n+1):
        print(dis[i])

'''
5 5
2 3 2
1 2 -3
1 5 5
4 5 2
3 4 3
'''


# 圖深度走訪

In [ ]:
import numpy as np
#從各點走到5的最短距離
'''
輸入驗證資料：
5 8
1 2 2
1 5 10
2 3 3
2 5 7
3 1 4
3 4 4
4 5 5
5 3 3
'''

# 初始化
min1=99999999       #表正無窮
book = np.zeros(101, dtype=np.int)  # 用來表示是否走過
e = np.zeros((101,101), dtype=np.int) # 用來儲存地圖資料

def dfs (cur, dis): #cur是目前所在城市編號
	global min1
	if dis > min1: return   #如果目前走過的路已經大於之前找到的最短路徑，返回
	if cur == n:            #判斷是否到目標城市
		if dis < min1:      
			min1 = dis      #更新最短距離
			return
	for j in range(1, n+1): #從1號城市到n號城市依次嘗試
		#判斷目前城市到城市j是否有路，並判斷是否再以走過的路逕中
		if e[cur][j] != 99999999 and book[j]==0 :
			book[j]=1  #標記城市已在路徑中
			dfs(j, dis+e[cur][j]) #從城市j再出發，繼續尋找目標城市
			book[j]=0 #前一部探索完畢後，取消對城市j的標記
	return

#初始化二維矩陣
n, m = map(int, input().split(' '))
for i in range(1, n+1):
	for j in range(1, n+1):
		if i==j: 
			e[i][j]=0
		else: 
			e[i][j]=99999999

#讀入城市之間的道路
for i in range(1, m+1):
	a, b, c = map(int, input().split(' '))
	e[a][b] = c #unidirectional

#從1號城市出發
book[1]=1 #標記1號城市已在路徑中
dfs(1, 0) #1表示目前所在城市編號，0表示已走過的路徑
print(min1) # 列印最短路徑


# 圖廣度學習

In [ ]:
import numpy as np

'''
輸入驗證資料：
5 7 1 5
1 2
1 3
2 3
2 4
3 4
3 5
4 5
'''
class note:
	def __init__(self):
		self.x = np.zeros(2501, dtype=np.int) #城市編號
		self.s = np.zeros(2501, dtype=np.int) #轉機次數

que = note()
book = np.zeros(51, dtype=np.int)
e = np.zeros((51,51), dtype=np.int)

flag = 0

n, m, start, end = map(int, input().split(' '))
# 初始化二維矩陣
for i in range(1, n+1):
	for j in range(1, n+1):
		if i==j:
			e[i][j]=0
		else:
			e[i][j]=99999999
#讀入城市間的航班
for i in range(1, m+1):
	a, b = map(int, input().split(' '))
	#這邊是無相圖！！！
	e[a][b]=1
	e[b][a]=1

#佇列初始化
head = 1
tail = 1

#從start城市出發，並加入到佇列
que.x[tail] = start
que.s[tail] = 0
tail += 1
book[1] = start #標記已加入佇列中

#當佇列不為空
while head<tail :
	cur = que.x[head] #目前佇列中首城市的編號
	for j in range(1, n+1): #從1~n依次嘗試
		#判斷從城市cur到城市j是否有航班，並判斷城市j是否已經在佇列中
		if e[cur][j] != 99999999 and book[j]==0 :
	    	#如果從城市cur到城市j有航班且城市ｊ不在佇列中，則將j城市加入佇列
			que.x[tail] = j
			que.s[tail] = que.s[head] +1 #轉機次數+1
			tail +=1
			book[j]=1 #標記城市已在佇列中

		#如果到達目標城市，停止擴展，任務結束，退出迴圈
		if que.x[tail] == end:
			flag = 1
			break
	if flag ==1:
		break

	# 當一個擴展結束後，要head++才能對後面的點再進行擴展
	head += 1

# 列印佇列中末尾最後一個點(目標城市)的步數，但tail是指向佇列尾的下一個位置，所以要-1
print (que.s[tail-1])
